Repository qpeace45/gitra, pull requests merged in 2019-06, with the labels that each got.

#8 nunomoto
  nunomotoText.rtf
Labels: bug, documentation, duplicate, enhancement, help wanted

#7 tanaking thank u
  README.md
Labels: enhancement

#6 レビューしてください！！！
  README.md
  kata.txt
Labels: bug

#5 tanaka
  test01
Labels: good first issue

#3 My final commits
  Tanpan.csv
Labels: bug

#2 create .gitignore
  .gitignore
  README.md
Labels: help wanted

#1 tanaka is Nintendo
  tanaka.cls
Labels: enhancement

#4 shwang
  README.md
Labels: duplicate, enhancement, good first issue, help wanted, question
